name: Docker Tunnel Workflow

on:
  workflow_dispatch:

jobs:
  run-docker-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull and Run Docker Image - Check Version
        run: |
          docker run lambdatest/tunnel:latest --version

      - name: Pull and Run Docker Image - Start Tunnel
        run: |
          docker run --name lt lambdatest/tunnel:latest --user vaneetb --key 8iwAZa7mEGu7pc41aIkNJpnvHFc5lcIgy1cF4joZatI0lWvP1u
